# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontact.proto\x12\x07\x63ontact\"K\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"]\n\x14\x43reateContactRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"(\n\x15\x43reateContactResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n ContactListRespectiveUserRequest\"O\n!ContactListRespectiveUserResponse\x12*\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x18.contact.ContactWithUser\"%\n\x12\x43ontactListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"8\n\x13\x43ontactListResponse\x12!\n\x07\x63ontact\x18\x01 \x03(\x0b\x32\x10.contact.Contact\"p\n\x0f\x43ontactWithUser\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x1b\n\x04user\x18\x05 \x01(\x0b\x32\r.contact.User\"F\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t2\xa4\x02\n\x0e\x43ontactService\x12P\n\rCreateContact\x12\x1d.contact.CreateContactRequest\x1a\x1e.contact.CreateContactResponse\"\x00\x12q\n\x16GetContactListWithUser\x12).contact.ContactListRespectiveUserRequest\x1a*.contact.ContactListRespectiveUserResponse\"\x00\x12M\n\x0eGetContactList\x12\x1b.contact.ContactListRequest\x1a\x1c.contact.ContactListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTACT']._serialized_start=26
  _globals['_CONTACT']._serialized_end=101
  _globals['_CREATECONTACTREQUEST']._serialized_start=103
  _globals['_CREATECONTACTREQUEST']._serialized_end=196
  _globals['_CREATECONTACTRESPONSE']._serialized_start=198
  _globals['_CREATECONTACTRESPONSE']._serialized_end=238
  _globals['_CONTACTLISTRESPECTIVEUSERREQUEST']._serialized_start=240
  _globals['_CONTACTLISTRESPECTIVEUSERREQUEST']._serialized_end=274
  _globals['_CONTACTLISTRESPECTIVEUSERRESPONSE']._serialized_start=276
  _globals['_CONTACTLISTRESPECTIVEUSERRESPONSE']._serialized_end=355
  _globals['_CONTACTLISTREQUEST']._serialized_start=357
  _globals['_CONTACTLISTREQUEST']._serialized_end=394
  _globals['_CONTACTLISTRESPONSE']._serialized_start=396
  _globals['_CONTACTLISTRESPONSE']._serialized_end=452
  _globals['_CONTACTWITHUSER']._serialized_start=454
  _globals['_CONTACTWITHUSER']._serialized_end=566
  _globals['_USER']._serialized_start=568
  _globals['_USER']._serialized_end=638
  _globals['_CONTACTSERVICE']._serialized_start=641
  _globals['_CONTACTSERVICE']._serialized_end=933
# @@protoc_insertion_point(module_scope)
